version: "{build}"

# os: Visual Studio 2015

branches:
  only:
    - jf-add-appveyor-build

skip_tags: true
clone_folder: c:\projects\atom
clone_depth: 10

environment:
  ATOM_DEV_RESOURCE_PATH: c:\projects\atom
  # GYP_MSVS_VERSION: 2015

install:
  - SET PATH=C:\Program Files\Atom\resources\cli;%PATH%
  - ps: Install-Product node 4.2.1

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - npm install
  - cf - cd %APPVEYOR_BUILD_FOLDER%\apm
  - npm install
  - SET PATH=C:\Program Files\Atom\resources\cli;%PATH%
  - c:\projects\atom\script\build.cmd

test: off
deploy: off
